### ISSUE TITLE
Start creates intelephense folder

### ISSUE THREAD

**Issue by halivert** [marlonfan/coc-phpls#32]
When phpls starts, it creates a folder in $HOME directory named "intelephense".

1. Open php file with nvim and coc-phpls extension activated.
2. See new folder in your $HOME directory

*Expected behavior*
No new folder in $HOME directory, or an option to configure directory creation.

*Desktop:*
 - OS: Arch Linux
 - Version 2.0.7

*Comments*
Thank you for your work I love this extension and want to improve it but I don't know how to do it.

**Comment by marlonfan** [comment]
It can recur. Let me check

----------

From&nbsp;樊凡.



--------------原始邮件--------------
发件人："Hali Velázquez "<notifications@github.com&gt;;
发送时间：2019年11月12日(星期二) 凌晨1:53
收件人："marlonfan/coc-phpls" <coc-phpls@noreply.github.com&gt;;
抄送："marlon "<marlon@tfan.net&gt;;"Assign "<assign@noreply.github.com&gt;;
主题：[marlonfan/coc-phpls] Start creates intelephense folder (#32)
-----------------------------------

 
When phpls starts, it creates a folder in $HOME directory named "intelephense".
 
Steps to reproduce the behavior:
  
Open php file with nvim and coc-phpls extension activated.
 
See new folder in your $HOME directory
  
Expected behavior
 No new folder in $HOME directory, or an option to configure directory creation.
 
Desktop:
  
OS: Arch Linux
 
Version 2.0.7
  
Comments
 Thank you for your work I love this extension and want to improve it but I don't know how to do it.

**Comment by marlonfan** [comment]
Can't reproduce now, can you reproduce there?

**Comment by halivert** [comment]
Yes, this is the described behavior

![intelephense folder created](https://user-images.githubusercontent.com/16197249/68921966-01ef9000-0740-11ea-979b-f6a4a4970bda.gif)

**Comment by marlonfan** [comment]
May I know your nvim version and coc.nvim version?

I think it seems to have something to do with them.

**Comment by halivert** [comment]
vim version: NVIM v0.5.0-163-g7116a41e3
node version: v13.1.0
coc.nvim version: 0.0.74-1ff50ec3b0

> May I know your nvim version and coc.nvim version?
> 
> I think it seems to have something to do with them.

**Comment by marlonfan** [comment]
Hi @halivert , This bug fixed. FYI: https://github.com/bmewburn/intelephense-docs/issues/13

**Comment by halivert** [comment]
Thank you for your time and efforts @marlonfan :+1: :relieved:
