### ISSUE TITLE
全局变量提示？？

### ISSUE THREAD

**Issue by solly0880** [marlonfan/coc-phpls#53]
问下，coc-phpls 是否支持显示 $_GET, $_POST, $_FILES 这类全局变量的提示？？

**Comment by cxgslegend** [comment]
There is a language barrier here. So I apologize if I misunderstood your question (I am using google translate). But I think you are asking if coc-phpls can complete globals like $_GET. The answer to that is yes. I am getting completion for these keywords. 

<img width="866" alt="Screen Shot 2020-07-12 at 10 09 33 PM" src="https://user-images.githubusercontent.com/8932713/87263996-cf439600-c48c-11ea-8465-84f5731cd82d.png">

Of course, I am using Laravel. So maybe it is just completing it because it saw it somewhere else in the Framework when it indexed the files. But even if that is true, worst case it won't work the first time you write one of these symbols. 

Also, if it is the second case, I believe intelephense supports adding default symbols through stubs ([Getting started page that has stubs section](https://github.com/bmewburn/intelephense-docs/blob/master/gettingStarted.md)).

Best of luck!
